/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/pi/catkin_ws/src/led/srv/Singular.srv
 *
 */


#ifndef LED_MESSAGE_SINGULAR_H
#define LED_MESSAGE_SINGULAR_H

#include <ros/service_traits.h>


#include <led/SingularRequest.h>
#include <led/SingularResponse.h>


namespace led
{

struct Singular
{

typedef SingularRequest Request;
typedef SingularResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Singular
} // namespace led


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led::Singular > {
  static const char* value()
  {
    return "9f6b1c627990bd77acebe28b6762cf08";
  }

  static const char* value(const ::led::Singular&) { return value(); }
};

template<>
struct DataType< ::led::Singular > {
  static const char* value()
  {
    return "led/Singular";
  }

  static const char* value(const ::led::Singular&) { return value(); }
};


// service_traits::MD5Sum< ::led::SingularRequest> should match 
// service_traits::MD5Sum< ::led::Singular > 
template<>
struct MD5Sum< ::led::SingularRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led::Singular >::value();
  }
  static const char* value(const ::led::SingularRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led::SingularRequest> should match 
// service_traits::DataType< ::led::Singular > 
template<>
struct DataType< ::led::SingularRequest>
{
  static const char* value()
  {
    return DataType< ::led::Singular >::value();
  }
  static const char* value(const ::led::SingularRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led::SingularResponse> should match 
// service_traits::MD5Sum< ::led::Singular > 
template<>
struct MD5Sum< ::led::SingularResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led::Singular >::value();
  }
  static const char* value(const ::led::SingularResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led::SingularResponse> should match 
// service_traits::DataType< ::led::Singular > 
template<>
struct DataType< ::led::SingularResponse>
{
  static const char* value()
  {
    return DataType< ::led::Singular >::value();
  }
  static const char* value(const ::led::SingularResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED_MESSAGE_SINGULAR_H
