/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/pi/catkin_ws/src/led/srv/Song.srv
 *
 */


#ifndef LED_MESSAGE_SONG_H
#define LED_MESSAGE_SONG_H

#include <ros/service_traits.h>


#include <led/SongRequest.h>
#include <led/SongResponse.h>


namespace led
{

struct Song
{

typedef SongRequest Request;
typedef SongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Song
} // namespace led


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led::Song > {
  static const char* value()
  {
    return "816ee56b071068f4c970381181d431b6";
  }

  static const char* value(const ::led::Song&) { return value(); }
};

template<>
struct DataType< ::led::Song > {
  static const char* value()
  {
    return "led/Song";
  }

  static const char* value(const ::led::Song&) { return value(); }
};


// service_traits::MD5Sum< ::led::SongRequest> should match 
// service_traits::MD5Sum< ::led::Song > 
template<>
struct MD5Sum< ::led::SongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led::Song >::value();
  }
  static const char* value(const ::led::SongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led::SongRequest> should match 
// service_traits::DataType< ::led::Song > 
template<>
struct DataType< ::led::SongRequest>
{
  static const char* value()
  {
    return DataType< ::led::Song >::value();
  }
  static const char* value(const ::led::SongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led::SongResponse> should match 
// service_traits::MD5Sum< ::led::Song > 
template<>
struct MD5Sum< ::led::SongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led::Song >::value();
  }
  static const char* value(const ::led::SongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led::SongResponse> should match 
// service_traits::DataType< ::led::Song > 
template<>
struct DataType< ::led::SongResponse>
{
  static const char* value()
  {
    return DataType< ::led::Song >::value();
  }
  static const char* value(const ::led::SongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED_MESSAGE_SONG_H
