/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/pi/catkin_ws/src/my_pkg/srv/Led.srv
 *
 */


#ifndef MY_PKG_MESSAGE_LED_H
#define MY_PKG_MESSAGE_LED_H

#include <ros/service_traits.h>


#include <my_pkg/LedRequest.h>
#include <my_pkg/LedResponse.h>


namespace my_pkg
{

struct Led
{

typedef LedRequest Request;
typedef LedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Led
} // namespace my_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_pkg::Led > {
  static const char* value()
  {
    return "6e5a67119d1df19e90f7d2dd1ffc147f";
  }

  static const char* value(const ::my_pkg::Led&) { return value(); }
};

template<>
struct DataType< ::my_pkg::Led > {
  static const char* value()
  {
    return "my_pkg/Led";
  }

  static const char* value(const ::my_pkg::Led&) { return value(); }
};


// service_traits::MD5Sum< ::my_pkg::LedRequest> should match 
// service_traits::MD5Sum< ::my_pkg::Led > 
template<>
struct MD5Sum< ::my_pkg::LedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_pkg::Led >::value();
  }
  static const char* value(const ::my_pkg::LedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_pkg::LedRequest> should match 
// service_traits::DataType< ::my_pkg::Led > 
template<>
struct DataType< ::my_pkg::LedRequest>
{
  static const char* value()
  {
    return DataType< ::my_pkg::Led >::value();
  }
  static const char* value(const ::my_pkg::LedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_pkg::LedResponse> should match 
// service_traits::MD5Sum< ::my_pkg::Led > 
template<>
struct MD5Sum< ::my_pkg::LedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_pkg::Led >::value();
  }
  static const char* value(const ::my_pkg::LedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_pkg::LedResponse> should match 
// service_traits::DataType< ::my_pkg::Led > 
template<>
struct DataType< ::my_pkg::LedResponse>
{
  static const char* value()
  {
    return DataType< ::my_pkg::Led >::value();
  }
  static const char* value(const ::my_pkg::LedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PKG_MESSAGE_LED_H
